### ISSUE TITLE
Left Swipe

### ISSUE THREAD

**Issue by rodriguezivanb** [chengdazhi/DecentBanner#15]
When it takes a slide to the left, appears blank space.

**Comment by chengdazhi** [comment]
@rodriguezivanb how many tabs do you have?

**Comment by liangzhiqi** [comment]
When it takes a slide to the left, appears blank space.    Two labels

**Comment by chengdazhi** [comment]
@liangzhiqi When you have less than 3 labels, you need to pass in no less than 3 views. This is because of the viewpager's loading scheme: viewpager loads 3 pages at a time. So when you have 2 labels, the view list you pass in the DecentBanner.start() method should contain 4 views, the first and the third are identical, and the second & fourth are identical, while the title list should have just 2 elements.
